import { useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { BookOpen, CheckCircle2, ChevronLeft, ChevronRight, FileText, ShieldCheck, Tag, Bell, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";
import { cn } from "@/lib/utils";
import { enablePushNotifications, getPushSubscription, pushNotificationsSupported } from "@/lib/pushNotifications";

// Profile completion is only for accounts created after this feature was introduced.
// Existing accounts are never forced into the new completion dialog.
const PROFILE_COMPLETION_ENABLED_FROM = "2026-09-28T12:30:00.000Z";


export function WelcomeOnboarding(){
 const {user,isAdmin,profile,loading:authLoading,refreshProfile}=useAuth();
 const [open,setOpen]=useState(false); const [step,setStep]=useState(1); const [profileCompleteOpen,setProfileCompleteOpen]=useState(false); const [completionName,setCompletionName]=useState(""); const [completionPhone,setCompletionPhone]=useState("+370"); const [completionExperience,setCompletionExperience]=useState(""); const [completionParentPhone,setCompletionParentPhone]=useState(false); const [completionBusy,setCompletionBusy]=useState(false); const [completionNeedsWelcome,setCompletionNeedsWelcome]=useState(false);
 const [notifyReminders,setNotifyReminders]=useState(true); const [notifyReminderHours,setNotifyReminderHours]=useState<5|24>(24); const [notifyChanges,setNotifyChanges]=useState(true); const [notifyNews,setNotifyNews]=useState(true);
 const [readToEnd,setReadToEnd]=useState(false); const [accepted,setAccepted]=useState(false); const [saving,setSaving]=useState(false); const [promptOpen,setPromptOpen]=useState(false); const [promptBusy,setPromptBusy]=useState(false); const scrollRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!user||authLoading||isAdmin)return;(async()=>{let{data,error}=await (supabase as any).from("profiles").select("onboarding_accepted_at,full_name,phone,experience_text,phone_is_parent").eq("id",user.id).maybeSingle();if(error){console.error("Equus onboarding profile load failed",error);toast.error("Nepavyko patikrinti pasveikinimo lango. Perkraukite puslapį.");return;}if(!data){const meta=(user.user_metadata||{}) as Record<string,unknown>;const fallbackName=String(meta.full_name||"").trim();const fallbackPhone=String(meta.phone||"").trim();const fallbackExperience=String(meta.experience_text||"").trim();const fallbackParent=meta.phone_is_parent===true;const{error:insertError}=await (supabase as any).from("profiles").upsert({id:user.id,full_name:fallbackName||((user.email||"").split("@")[0]||"Equus klientas"),phone:fallbackPhone||null,experience_text:fallbackExperience||null,phone_is_parent:fallbackParent},{onConflict:"id"});if(insertError){console.error("Equus onboarding profile create failed",insertError);toast.error("Nepavyko paruošti jūsų Equus profilio. Perkraukite puslapį.");return;}const refreshed=await (supabase as any).from("profiles").select("onboarding_accepted_at,full_name,phone,experience_text,phone_is_parent").eq("id",user.id).maybeSingle();if(refreshed.error||!refreshed.data){console.error("Equus onboarding profile reload failed",refreshed.error);return;}data=refreshed.data;}const savedName=(data?.full_name||profile?.full_name||"").trim();const email=(user.email||"").trim().toLowerCase();const nameLooksLikeEmail=!!savedName&&savedName.toLowerCase()===email;setCompletionName(nameLooksLikeEmail?"":savedName);setCompletionPhone(data?.phone ? String(data.phone) : "+370");setCompletionExperience(data?.experience_text||"");setCompletionParentPhone(!!data?.phone_is_parent);const isNewUser = new Date(user.created_at).getTime() >= new Date(PROFILE_COMPLETION_ENABLED_FROM).getTime();if(isNewUser&&(!savedName||nameLooksLikeEmail||!data?.phone||!data?.experience_text)){setCompletionNeedsWelcome(!data?.onboarding_accepted_at);setProfileCompleteOpen(true);return;}if(!data?.onboarding_accepted_at){setStep(1);setReadToEnd(false);setAccepted(false);setOpen(true);return;}if(pushNotificationsSupported()){const{data:notificationData,error:notificationError}=await (supabase as any).from("profiles").select("notification_prompt_seen_at").eq("id",user.id).maybeSingle();if(!notificationError){const sub=await getPushSubscription();if(!sub && Notification.permission!=="denied" && !notificationData?.notification_prompt_seen_at){setPromptOpen(true);}}}})()},[user,isAdmin,profile,authLoading]);
 const saveProfileCompletion=async()=>{if(!user)return;const cleanName=completionName.trim();if(cleanName.length<2||cleanName.includes("@")){toast.error("Įveskite tikrą raitelio vardą ir pavardę.");return;}if(completionPhone.trim().length<6){toast.error("Įveskite telefono numerį.");return;}if(completionExperience.trim().length<30){toast.error("Aprašykite jojimo patirtį bent 30 simbolių.");return;}setCompletionBusy(true);const{error}=await (supabase as any).from("profiles").update({full_name:completionName.trim(),phone:completionPhone.trim(),experience_text:completionExperience.trim(),phone_is_parent:completionParentPhone}).eq("id",user.id);setCompletionBusy(false);if(error){toast.error("Nepavyko išsaugoti profilio.");return}await refreshProfile();setProfileCompleteOpen(false);if(completionNeedsWelcome){setStep(1);setReadToEnd(false);setAccepted(false);setOpen(true);setCompletionNeedsWelcome(false);}toast.success("Profilis užpildytas.");};
 const atBottom=(el:HTMLDivElement)=>el.scrollTop+el.clientHeight>=el.scrollHeight-40;
 const onScroll=()=>{const el=scrollRef.current;if(el&&atBottom(el))setReadToEnd(true)};
 // Kai kuriuose ekranuose turinys telpa be slinkimo (arba PDF perima slinkimą),
 // todėl tikriname periodiškai, kad varnelė netaptų neįjungiama.
 useEffect(()=>{if(step!==3)return;const check=()=>{const el=scrollRef.current;if(el&&atBottom(el))setReadToEnd(true)};check();const t=window.setInterval(check,400);window.addEventListener("resize",check);return()=>{window.clearInterval(t);window.removeEventListener("resize",check)}},[step]);
 const finish=async()=>{if(!user||!readToEnd||!accepted)return;setSaving(true);const{error}=await (supabase as any).from("profiles").update({onboarding_accepted_at:new Date().toISOString(),rules_version:"2026-08",notify_lesson_reminders:notifyReminders,notify_schedule_changes:notifyChanges,notify_school_news:notifyNews,notify_lesson_reminder_hours:notifyReminderHours}).eq("id",user.id);if(error){setSaving(false);toast.error("Nepavyko išsaugoti");return}if((notifyReminders||notifyChanges||notifyNews)&&pushNotificationsSupported()){try{await enablePushNotifications("lt")}catch(e:any){toast.error(e?.message||"Nepavyko įjungti pranešimų");}}await refreshProfile();setSaving(false);toast.success("Sveiki atvykę į Equus 🐴");setOpen(false)};
 const markPromptSeen=async()=>{if(user)await (supabase as any).from("profiles").update({notification_prompt_seen_at:new Date().toISOString()}).eq("id",user.id);};
 const enablePrompt=async()=>{setPromptBusy(true);try{await enablePushNotifications("lt");await markPromptSeen();setPromptOpen(false);toast.success("Equus pranešimai įjungti 🐴");}catch(e:any){toast.error(e?.message||"Nepavyko įjungti pranešimų");}finally{setPromptBusy(false)}};
 const dismissPrompt=async()=>{await markPromptSeen();setPromptOpen(false)};
 return <><Dialog open={open} onOpenChange={()=>undefined}><DialogContent className="grid h-[100dvh] max-h-[100dvh] w-screen max-w-none grid-rows-[auto_minmax(0,1fr)_auto] gap-0 overflow-hidden border-gold/30 bg-card p-0 sm:h-auto sm:max-h-[92dvh] sm:w-[calc(100%-2rem)] sm:max-w-3xl sm:rounded-2xl" onEscapeKeyDown={e=>e.preventDefault()} onPointerDownOutside={e=>e.preventDefault()}>
  <DialogHeader className="border-b border-border bg-gradient-card px-4 py-4 pr-10 sm:px-6"><DialogTitle className="font-display text-2xl text-gradient-gold sm:text-3xl">Sveiki atvykę į Equus jojimo mokyklą!</DialogTitle><div className="mt-3 grid grid-cols-3 gap-2">{[1,2,3].map(n=><div key={n} className={cn("h-1.5 rounded-full",n<=step?"bg-gold":"bg-muted")}/>)}</div></DialogHeader>
  <div ref={scrollRef} onScroll={onScroll} className="min-h-0 overflow-y-auto px-4 py-5 sm:px-6">
   {step===1&&<div><h3 className="font-display text-2xl">Pasirinkite svetainės temą</h3><p className="mt-2 text-sm text-muted-foreground">Temą ir šviesumą vėliau galėsite pakeisti savo paskyroje.</p><div className="mt-5"><ThemeSwitcher/></div></div>}
   {step===2&&<div><h3 className="font-display text-2xl">Pranešimai</h3><p className="mt-2 text-sm text-muted-foreground">Pasirinkite, kokius svarbius pranešimus norite gauti. Tai nėra reklama.</p><div className="mt-5 space-y-3">{[[notifyReminders,setNotifyReminders,"Treniruotės priminimai"],[notifyChanges,setNotifyChanges,"Svarbūs grafiko pakeitimai"],[notifyNews,setNotifyNews,"Svarbios mokyklos naujienos"]].map(([v,setter,label]:any)=><label key={label} className="flex cursor-pointer items-center gap-3 rounded-xl border p-4"><Checkbox checked={v} onCheckedChange={x=>setter(x===true)}/><span>{label}</span></label>)}{notifyReminders&&<div className="rounded-xl border border-gold/15 bg-background/30 p-4"><p className="text-sm font-medium">Kada priminti apie treniruotę?</p><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setNotifyReminderHours(24)} className={cn("rounded-lg border px-3 py-2 text-sm",notifyReminderHours===24?"border-gold bg-gold/10 text-gold":"border-border")}>24 val. prieš</button><button type="button" onClick={()=>setNotifyReminderHours(5)} className={cn("rounded-lg border px-3 py-2 text-sm",notifyReminderHours===5?"border-gold bg-gold/10 text-gold":"border-border")}>5 val. prieš</button></div></div>}</div></div>}
   {step===3&&<div><div className="grid gap-3 sm:grid-cols-2"><Card icon={ShieldCheck} title="Atšaukimo tvarka">Atšaukimas galimas 24 val. prieš treniruotę. Pavėluotai atšaukta treniruotė skaičiuojama kaip panaudota, išskyrus ligą ar force majeure.</Card><Card icon={Tag} title="Kainos">Aktualios kainos pateikiamos skiltyje „Kainos“.</Card><Card icon={FileText} title="Sutartis">Prieš pirmą treniruotę nepamirškite pasirašyti jojimo sutarties.</Card><Card icon={BookOpen} title="Žirgyno taisyklės">Atvykite maždaug 30 min. anksčiau ir dėvėkite tinkamą avalynę.</Card></div><div className="mt-4 rounded-2xl border border-gold/20 p-4"><div className="mb-3 flex justify-between"><div><h3 className="font-display text-xl">Sutartis ir taisyklės</h3><p className="text-xs text-muted-foreground">Perskaitykite iki apačios.</p></div><a href="/equus-sutartis-ir-taisykles.pdf" target="_blank" className="text-sm text-gold underline">Atidaryti PDF</a></div><iframe title="Sutartis" src="/equus-sutartis-ir-taisykles.pdf#toolbar=0" className="h-[260px] w-full rounded-lg border bg-white sm:h-[360px]"/></div><p className="mt-5 text-sm">Daugiau informacijos rasite <Link to="/informacija" target="_blank" className="text-gold underline">Informacijos puslapyje</Link>.</p><div className="min-h-20 pt-8 text-center text-xs text-muted-foreground">{readToEnd?<span className="inline-flex items-center gap-1 text-emerald-500"><CheckCircle2 className="h-4 w-4"/>Perskaitėte iki galo</span>:"Slinkite iki pat pabaigos."}</div></div>}
  </div>
  <div className="border-t border-border bg-card px-4 py-3 pb-[max(.75rem,env(safe-area-inset-bottom))] sm:px-6">{step===3&&<label className={cn("mb-3 flex items-start gap-3 rounded-lg border p-3",!readToEnd&&"opacity-50")}><Checkbox checked={accepted} disabled={!readToEnd} onCheckedChange={v=>setAccepted(v===true)}/><span className="text-sm">Susipažinau su taisyklėmis, kainomis, atšaukimo tvarka ir sutarties priminimu.</span></label>}<div className="flex justify-between"><Button variant="ghost" disabled={step===1} onClick={()=>setStep(s=>s-1)}><ChevronLeft className="h-4 w-4"/>Atgal</Button>{step<3?<Button variant="gold" onClick={()=>setStep(s=>s+1)}>Toliau<ChevronRight className="h-4 w-4"/></Button>:<Button variant="gold" disabled={!readToEnd||!accepted||saving} onClick={finish}>{saving?"Išsaugoma…":"Sutinku ir tęsiu"}</Button>}</div></div>
 </DialogContent></Dialog>

  <Dialog open={profileCompleteOpen} onOpenChange={()=>undefined}>
   <DialogContent className="border-gold/25 bg-gradient-card sm:max-w-lg">
    <DialogHeader><DialogTitle className="font-display text-2xl text-gradient-gold">Užbaikime jūsų Equus profilį</DialogTitle></DialogHeader>
    <div className="space-y-4">
      <p className="text-sm text-muted-foreground">Google pateikė jūsų vardą ir el. paštą. Dar reikia kelių Equus registracijai reikalingų duomenų.</p>
      <div><label className="text-sm font-medium">Vardas ir pavardė</label><Input value={completionName} onChange={e=>setCompletionName(e.target.value)} maxLength={80} /></div>
      <div><label className="text-sm font-medium">Telefono numeris</label><Input type="tel" value={completionPhone} onChange={e=>{const next=e.target.value.replace(/[^0-9+]/g,"");setCompletionPhone(next.startsWith("+370")?next:next.replace(/^\+?370/,"+370").replace(/^\+?/,"+370"));}} placeholder="+370 6…" maxLength={20} />
        <label className="mt-2 flex cursor-pointer items-start gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={completionParentPhone} onChange={e=>setCompletionParentPhone(e.target.checked)} className="mt-0.5 h-4 w-4 accent-[hsl(var(--gold))]" /><span>Tai tėvų / globėjo numeris (raitelis – vaikas)</span></label>
      </div>
      <div><label className="text-sm font-medium">Jojimo patirtis</label><textarea value={completionExperience} onChange={e=>setCompletionExperience(e.target.value)} minLength={30} maxLength={30} rows={5} className="mt-1 flex w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Kiek laiko jodinėjate, ką mokate, ar turite varžybų patirties…" /><p className="mt-1 text-xs text-muted-foreground">{completionExperience.trim().length}/30</p></div>
    </div>
    <div className="flex justify-end pt-2"><Button variant="gold" onClick={saveProfileCompletion} disabled={completionBusy}>{completionBusy?"Saugoma…":"Tęsti"}</Button></div>
  </DialogContent>
 </Dialog>

  <Dialog open={promptOpen} onOpenChange={(next)=>{if(!next&&!promptBusy)dismissPrompt();}}>
   <DialogContent className="border-gold/25 bg-gradient-card sm:max-w-md">
    <DialogHeader><DialogTitle className="font-display text-2xl text-gradient-gold flex items-center gap-2"><Bell className="h-5 w-5 text-gold"/>Equus pranešimai</DialogTitle></DialogHeader>
    <div className="space-y-4">
     <div className="rounded-2xl border border-gold/15 bg-background/30 p-4"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 h-5 w-5 shrink-0 text-gold"/><p className="text-sm leading-6 text-muted-foreground">Gaukite svarbius Equus atnaujinimus, pavyzdžiui, apie atšauktas ar perkeltas treniruotes, ir pasirinktinus treniruočių priminimus.</p></div></div>
     <p className="text-sm text-muted-foreground">Šiuos nustatymus vėliau galėsite pakeisti savo paskyroje.</p>
    </div>
    <div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="ghost" onClick={dismissPrompt} disabled={promptBusy}>Ne dabar</Button><Button variant="gold" onClick={enablePrompt} disabled={promptBusy}>{promptBusy?"Įjungiama…":"Įjungti pranešimus"}</Button></div>
   </DialogContent>
  </Dialog></>;
}
function Card({icon:Icon,title,children}:{icon:any;title:string;children:ReactNode}){return <div className="rounded-2xl border bg-background/35 p-4"><Icon className="mb-2 h-5 w-5 text-gold"/><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{children}</p></div>}
